import { IVideo } from '../types/data.interface';

export const recommendVideo: IVideo[] = [
	{
		title: '겟투웤 켠왕',
		name: '초승달',
		category: [3, 9],
		isLive: true,
		src: '/images/data/recommend1.png',
		watchingCount: 352,
		streamerImg: '/images/data/streamer1.png',
	},
	{
		title: '오늘은 레전드 얼리버드 먹방',
		name: '스나링',
		category: [4, 12],
		isLive: true,
		src: '/images/data/recommend2.png',
		watchingCount: 975,
		streamerImg: '/images/data/streamer2.png',
	},
	{
		title: '반갑습니다 지구인들',
		name: '나나양',
		category: [6, 10],
		isLive: true,
		src: '/images/data/recommend3.png',
		watchingCount: 653,
		streamerImg: '/images/data/streamer3.png',
	},
	{
		title: '3대 500 못해?',
		name: '헬창남',
		category: [12, 10],
		isLive: true,
		src: '/images/data/recommend4.png',
		watchingCount: 90,
		streamerImg: '/images/data/streamer4.png',
	},
	{
		title: '우리집 강아지가 최고',
		name: '마루는강아지',
		category: [3, 8],
		isLive: true,
		src: '/images/data/recommend5.png',
		watchingCount: 542,
		streamerImg: '/images/data/streamer5.png',
	},
	{
		title: '또 나올 수 있을까?',
		name: 'JISOO',
		category: [1, 4, 8],
		isLive: true,
		src: '/images/data/recommend6.png',
		watchingCount: 763,
		streamerImg: '/images/data/streamer6.png',
	},
];

export const followingVideo: IVideo[] = [
	{
		title: '태국 편의점 먹방',
		name: '랄랄루',
		category: [7, 9],
		isLive: true,
		src: '/images/data/following1.png',
		watchingCount: 145,
		streamerImg: '/images/data/streamer7.png',
	},
	{
		title: '훈육해야 한다 VS 안 해야 한다?',
		name: '리쥬리쥬리',
		category: [5, 6],
		isLive: true,
		src: '/images/data/following2.png',
		watchingCount: 236,
		streamerImg: '/images/data/streamer8.png',
	},
	{
		title: '잠실 소피텔 럭셔리 호캉스',
		name: '후눙한생활인',
		category: [1, 8],
		isLive: true,
		src: '/images/data/following3.png',
		watchingCount: 744,
		streamerImg: '/images/data/streamer9.png',
	},
	{
		title: '장기연애 후에 하는 연애',
		name: '픽픽고고링',
		category: [11, 12],
		isLive: true,
		src: '/images/data/following4.png',
		watchingCount: 190,
		streamerImg: '/images/data/streamer10.png',
	},
	{
		title: '마이혁이라고 불러도 돼?',
		name: '대상혁',
		category: [3, 5],
		isLive: true,
		src: '/images/data/following5.png',
		watchingCount: 895,
		streamerImg: '/images/data/streamer11.png',
	},
	{
		title: '2025 LCK CUP 그룹 배틀',
		name: 'LCK',
		category: [1, 9],
		isLive: true,
		src: '/images/data/following6.png',
		watchingCount: 347,
		streamerImg: '/images/data/streamer12.png',
	},
];

export const liveVideo: IVideo[] = [
	{
		title: '카지노 시즌2 몰아보기',
		name: '공작새TV',
		category: [4, 10],
		isLive: true,
		src: '/images/data/live1.png',
		watchingCount: 234,
		streamerImg: '/images/data/streamer13.png',
	},
	{
		title: '오징어게임2 남수의 짜증나는 연기',
		name: '숏잼맨',
		category: [5, 12],
		isLive: true,
		src: '/images/data/live2.png',
		watchingCount: 176,
		streamerImg: '/images/data/streamer14.png',
	},
	{
		title: '치대생이 알려주는 치과 방문 시 꿀팁',
		name: 'ootd STUDIO',
		category: [3, 10],
		isLive: true,
		src: '/images/data/live3.png',
		watchingCount: 295,
		streamerImg: '/images/data/streamer15.png',
	},
	{
		title: '털털한 송혜교 어떤데',
		name: '태희혜교지현',
		category: [1, 4],
		isLive: true,
		src: '/images/data/live4.png',
		watchingCount: 996,
		streamerImg: '/images/data/streamer16.png',
	},
	{
		title: '애들아 나 헤어짐ㅋ',
		name: '롱박스',
		category: [7, 9],
		isLive: true,
		src: '/images/data/live5.png',
		watchingCount: 234,
		streamerImg: '/images/data/streamer17.png',
	},
	{
		title: '수많은 억까를 분석해서 집으로 돌아가는 게임',
		name: 'JISOO',
		category: [10, 12],
		isLive: true,
		src: '/images/data/live6.png',
		watchingCount: 467,
		streamerImg: '/images/data/streamer18.png',
	},
];

export const category = [
	{
		title: '스나',
		image: '/images/data/category1.png',
		watchingCount: 125679,
	},
	{
		title: 'gta',
		image: '/images/data/category2.png',
		watchingCount: 85567,
	},
	{
		title: 'LOL',
		image: '/images/data/category3.png',
		watchingCount: 64523,
	},
	{
		title: '바람의나라',
		image: '/images/data/category4.png',
		watchingCount: 67542,
	},
	{
		title: '로스트아크',
		image: '/images/data/category5.png',
		watchingCount: 387943,
	},
	{
		title: 'TFT',
		image: '/images/data/category6.png',
		watchingCount: 257889,
	},
	{
		title: '어몽어스',
		image: '/images/data/category7.png',
		watchingCount: 73463,
	},
	{
		title: 'FIFAONLINE4',
		image: '/images/data/category8.png',
		watchingCount: 330586,
	},
	{
		title: '마인크래프트',
		image: '/images/data/category9.png',
		watchingCount: 45712,
	},
	{
		title: '동물의숲',
		image: '/images/data/category10.png',
		watchingCount: 158936,
	},
	{
		title: '오버워치',
		image: '/images/data/category11.png',
		watchingCount: 46822,
	},
	{
		title: '월드오브크래프트',
		image: '/images/data/category12.png',
		watchingCount: 90476,
	},
];
