name: CI and PR Workflow

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃 (브랜치 전체 히스토리 가져오기)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리를 가져옵니다.

      # 2. Node.js 및 Yarn 설정
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # 3. 의존성 설치
      - name: Install dependencies
        run: yarn install

      # 4. 빌드 실행
      - name: Run Build
        run: yarn build

      # 5. dev → main PR 생성
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR: Sync dev to main"
          body: "This PR was automatically created to sync dev with main."
          base: main
          branch: dev  # 변경 사항이 이미 dev에 있기 때문에 강제 푸시 불필요
