name: CI Workflow

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Build
        run: |
          yarn build

      - name: Create PR to main
        if: github.event_name == 'push'
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: main
          pr_title: "Automated PR: Sync dev to main"
          pr_body: "This PR was automatically created to sync dev with main."
          github_token: ${{ secrets.GITHUB_TOKEN }}
